//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int id { get; set; }
        public int beaconId { get; set; }
        public int beaconRss { get; set; }
        public int userId { get; set; }
    }
}
