//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServerClient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ble_projectEntities1 : DbContext
    {
        public ble_projectEntities1()
            : base("name=ble_projectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beacon> Beacon { get; set; }
        public virtual DbSet<Connection> Connection { get; set; }
        public virtual DbSet<PeopleCounting> PeopleCounting { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
