//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleCounting
    {
        public int id { get; set; }
        public int storeId { get; set; }
        public long Girenler { get; set; }
        public long Cikanlar { get; set; }
        public System.DateTime Date { get; set; }
    }
}
